// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFitcM0QOqU2LU57OVdENA2ZxDzfQlzs',
    appId: '1:997700572273:web:da99e911b4f4cbca76b7d0',
    messagingSenderId: '997700572273',
    projectId: 'cmsc23-todo-app-hbsamson',
    authDomain: 'cmsc23-todo-app-hbsamson.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-hbsamson.appspot.com',
    measurementId: 'G-KS737K0NG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5aJ5kHYmDyAcB0_3WHSUdInZdk__YOqE',
    appId: '1:997700572273:android:442c434493f0ade176b7d0',
    messagingSenderId: '997700572273',
    projectId: 'cmsc23-todo-app-hbsamson',
    storageBucket: 'cmsc23-todo-app-hbsamson.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXb2rLKFXHOLVxnt50VTmqvSigsVhBrKs',
    appId: '1:997700572273:ios:57abd5a8929eccf576b7d0',
    messagingSenderId: '997700572273',
    projectId: 'cmsc23-todo-app-hbsamson',
    storageBucket: 'cmsc23-todo-app-hbsamson.appspot.com',
    iosClientId: '997700572273-hmao1isa48fj97me8g72l6s1o1s7u9n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXb2rLKFXHOLVxnt50VTmqvSigsVhBrKs',
    appId: '1:997700572273:ios:57abd5a8929eccf576b7d0',
    messagingSenderId: '997700572273',
    projectId: 'cmsc23-todo-app-hbsamson',
    storageBucket: 'cmsc23-todo-app-hbsamson.appspot.com',
    iosClientId: '997700572273-hmao1isa48fj97me8g72l6s1o1s7u9n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
